/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTIME_H
#define _MOCKTIME_H

#include "unity.h"
#include "time.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mocktime_Init(void);
void Mocktime_Destroy(void);
void Mocktime_Verify(void);




#define wait_ms_Expect(ms) wait_ms_CMockExpect(__LINE__, ms)
void wait_ms_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ms);
#define wait_us_Expect(us) wait_us_CMockExpect(__LINE__, us)
void wait_us_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t us);
#define system_pll_clock_init_Expect(mul) system_pll_clock_init_CMockExpect(__LINE__, mul)
void system_pll_clock_init_CMockExpect(UNITY_LINE_TYPE cmock_line, PLLMul mul);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
