/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKGPIO_INTERFACE_H
#define _MOCKGPIO_INTERFACE_H

#include "unity.h"
#include "gpio_interface.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockgpio_interface_Init(void);
void Mockgpio_interface_Destroy(void);
void Mockgpio_interface_Verify(void);




#define gpio_port_enable_Expect(port) gpio_port_enable_CMockExpect(__LINE__, port)
void gpio_port_enable_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_Port port);
#define gpio_port_disable_Expect(port) gpio_port_disable_CMockExpect(__LINE__, port)
void gpio_port_disable_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_Port port);
#define gpio_lock_pin_ExpectAndReturn(rcc_devid, pin, cmock_retval) gpio_lock_pin_CMockExpectAndReturn(__LINE__, rcc_devid, pin, cmock_retval)
void gpio_lock_pin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RCC_DevId rcc_devid, GPIO_Pin pin, GPIO_Err cmock_to_return);
#define gpio_unlock_pin_ExpectAndReturn(rcc_devid, pin, cmock_retval) gpio_unlock_pin_CMockExpectAndReturn(__LINE__, rcc_devid, pin, cmock_retval)
void gpio_unlock_pin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RCC_DevId rcc_devid, GPIO_Pin pin, GPIO_Err cmock_to_return);
#define gpio_pin_config_Expect(pin, mode, config) gpio_pin_config_CMockExpect(__LINE__, pin, mode, config)
void gpio_pin_config_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_Pin pin, GPIO_Mode mode, GPIO_Config config);
#define gpio_pin_input_ExpectAndReturn(pin, cmock_retval) gpio_pin_input_CMockExpectAndReturn(__LINE__, pin, cmock_retval)
void gpio_pin_input_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GPIO_Pin pin, GPIO_State cmock_to_return);
#define gpio_pin_output_Expect(pin, state) gpio_pin_output_CMockExpect(__LINE__, pin, state)
void gpio_pin_output_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_Pin pin, GPIO_State state);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
