/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKRCC_INTERFACE_H
#define _MOCKRCC_INTERFACE_H

#include "unity.h"
#include "rcc_interface.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockrcc_interface_Init(void);
void Mockrcc_interface_Destroy(void);
void Mockrcc_interface_Verify(void);




#define rcc_pcendis_Expect(devid, on) rcc_pcendis_CMockExpect(__LINE__, devid, on)
void rcc_pcendis_CMockExpect(UNITY_LINE_TYPE cmock_line, RCC_DevId devid, bool on);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
