/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMMIO_OPS_H
#define _MOCKMMIO_OPS_H

#include "unity.h"
#include "mmio_ops.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockmmio_ops_Init(void);
void Mockmmio_ops_Destroy(void);
void Mockmmio_ops_Verify(void);




#define mmio_or_writeb_Expect(base, data) mmio_or_writeb_CMockExpect(__LINE__, base, data)
void mmio_or_writeb_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint8_t data);
#define mmio_or_writew_Expect(base, data) mmio_or_writew_CMockExpect(__LINE__, base, data)
void mmio_or_writew_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint16_t data);
#define mmio_or_writedw_Expect(base, data) mmio_or_writedw_CMockExpect(__LINE__, base, data)
void mmio_or_writedw_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint32_t data);
#define mmio_and_writeb_Expect(base, data) mmio_and_writeb_CMockExpect(__LINE__, base, data)
void mmio_and_writeb_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint8_t data);
#define mmio_and_writew_Expect(base, data) mmio_and_writew_CMockExpect(__LINE__, base, data)
void mmio_and_writew_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint16_t data);
#define mmio_and_writedw_Expect(base, data) mmio_and_writedw_CMockExpect(__LINE__, base, data)
void mmio_and_writedw_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint32_t data);
#define mmio_writeb_Expect(base, data) mmio_writeb_CMockExpect(__LINE__, base, data)
void mmio_writeb_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint8_t data);
#define mmio_writew_Expect(base, data) mmio_writew_CMockExpect(__LINE__, base, data)
void mmio_writew_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint16_t data);
#define mmio_writedw_Expect(base, data) mmio_writedw_CMockExpect(__LINE__, base, data)
void mmio_writedw_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint32_t data);
#define mmio_readb_ExpectAndReturn(base, cmock_retval) mmio_readb_CMockExpectAndReturn(__LINE__, base, cmock_retval)
void mmio_readb_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint8_t cmock_to_return);
#define mmio_readw_ExpectAndReturn(base, cmock_retval) mmio_readw_CMockExpectAndReturn(__LINE__, base, cmock_retval)
void mmio_readw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint16_t cmock_to_return);
#define mmio_readdw_ExpectAndReturn(base, cmock_retval) mmio_readdw_CMockExpectAndReturn(__LINE__, base, cmock_retval)
void mmio_readdw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint32_t cmock_to_return);
#define mmio_and_readb_ExpectAndReturn(base, mask, cmock_retval) mmio_and_readb_CMockExpectAndReturn(__LINE__, base, mask, cmock_retval)
void mmio_and_readb_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint8_t mask, uint8_t cmock_to_return);
#define mmio_and_readw_ExpectAndReturn(base, mask, cmock_retval) mmio_and_readw_CMockExpectAndReturn(__LINE__, base, mask, cmock_retval)
void mmio_and_readw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint16_t mask, uint16_t cmock_to_return);
#define mmio_and_readdw_ExpectAndReturn(base, mask, cmock_retval) mmio_and_readdw_CMockExpectAndReturn(__LINE__, base, mask, cmock_retval)
void mmio_and_readdw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint32_t mask, uint32_t cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
