/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockrcc_interface.h"

static const char* CMockString_devid = "devid";
static const char* CMockString_on = "on";
static const char* CMockString_rcc_pcendis = "rcc_pcendis";

typedef struct _CMOCK_rcc_pcendis_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RCC_DevId Expected_devid;
  bool Expected_on;

} CMOCK_rcc_pcendis_CALL_INSTANCE;

static struct Mockrcc_interfaceInstance
{
  CMOCK_MEM_INDEX_TYPE rcc_pcendis_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockrcc_interface_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.rcc_pcendis_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_rcc_pcendis);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockrcc_interface_Init(void)
{
  Mockrcc_interface_Destroy();
}

void Mockrcc_interface_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void rcc_pcendis(RCC_DevId devid, bool on)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rcc_pcendis_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rcc_pcendis);
  cmock_call_instance = (CMOCK_rcc_pcendis_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rcc_pcendis_CallInstance);
  Mock.rcc_pcendis_CallInstance = CMock_Guts_MemNext(Mock.rcc_pcendis_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_rcc_pcendis,CMockString_devid);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_devid), (void*)(&devid), sizeof(RCC_DevId), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_rcc_pcendis,CMockString_on);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_on, on, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rcc_pcendis(CMOCK_rcc_pcendis_CALL_INSTANCE* cmock_call_instance, RCC_DevId devid, bool on);
void CMockExpectParameters_rcc_pcendis(CMOCK_rcc_pcendis_CALL_INSTANCE* cmock_call_instance, RCC_DevId devid, bool on)
{
  memcpy((void*)(&cmock_call_instance->Expected_devid), (void*)(&devid),
         sizeof(RCC_DevId[sizeof(devid) == sizeof(RCC_DevId) ? 1 : -1])); /* add RCC_DevId to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_on = on;
}

void rcc_pcendis_CMockExpect(UNITY_LINE_TYPE cmock_line, RCC_DevId devid, bool on)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rcc_pcendis_CALL_INSTANCE));
  CMOCK_rcc_pcendis_CALL_INSTANCE* cmock_call_instance = (CMOCK_rcc_pcendis_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rcc_pcendis_CallInstance = CMock_Guts_MemChain(Mock.rcc_pcendis_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rcc_pcendis(cmock_call_instance, devid, on);
}

