/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockirq.h"

static const char* CMockString_h = "h";
static const char* CMockString_irq = "irq";
static const char* CMockString_irq_deregister_exception_handler = "irq_deregister_exception_handler";
static const char* CMockString_irq_deregister_interrupt_handler = "irq_deregister_interrupt_handler";
static const char* CMockString_irq_disable_interrupt = "irq_disable_interrupt";
static const char* CMockString_irq_enable_interrupt = "irq_enable_interrupt";
static const char* CMockString_irq_get_interrupt_status = "irq_get_interrupt_status";
static const char* CMockString_irq_register_exception_handler = "irq_register_exception_handler";
static const char* CMockString_irq_register_interrupt_handler = "irq_register_interrupt_handler";
static const char* CMockString_n = "n";

typedef struct _CMOCK_irq_register_interrupt_handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Interrupt_IRQn Expected_n;
  __irq_handler Expected_h;

} CMOCK_irq_register_interrupt_handler_CALL_INSTANCE;

typedef struct _CMOCK_irq_deregister_interrupt_handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Interrupt_IRQn Expected_n;

} CMOCK_irq_deregister_interrupt_handler_CALL_INSTANCE;

typedef struct _CMOCK_irq_register_exception_handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Exception_IRQn Expected_n;
  __irq_handler Expected_h;

} CMOCK_irq_register_exception_handler_CALL_INSTANCE;

typedef struct _CMOCK_irq_deregister_exception_handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Exception_IRQn Expected_n;

} CMOCK_irq_deregister_exception_handler_CALL_INSTANCE;

typedef struct _CMOCK_irq_enable_interrupt_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Interrupt_IRQn Expected_irq;

} CMOCK_irq_enable_interrupt_CALL_INSTANCE;

typedef struct _CMOCK_irq_get_interrupt_status_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  Interrupt_IRQn Expected_irq;

} CMOCK_irq_get_interrupt_status_CALL_INSTANCE;

typedef struct _CMOCK_irq_disable_interrupt_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Interrupt_IRQn Expected_irq;

} CMOCK_irq_disable_interrupt_CALL_INSTANCE;

static struct MockirqInstance
{
  CMOCK_MEM_INDEX_TYPE irq_register_interrupt_handler_CallInstance;
  CMOCK_MEM_INDEX_TYPE irq_deregister_interrupt_handler_CallInstance;
  CMOCK_MEM_INDEX_TYPE irq_register_exception_handler_CallInstance;
  CMOCK_MEM_INDEX_TYPE irq_deregister_exception_handler_CallInstance;
  CMOCK_MEM_INDEX_TYPE irq_enable_interrupt_CallInstance;
  CMOCK_MEM_INDEX_TYPE irq_get_interrupt_status_CallInstance;
  CMOCK_MEM_INDEX_TYPE irq_disable_interrupt_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockirq_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.irq_register_interrupt_handler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_irq_register_interrupt_handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.irq_deregister_interrupt_handler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_irq_deregister_interrupt_handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.irq_register_exception_handler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_irq_register_exception_handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.irq_deregister_exception_handler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_irq_deregister_exception_handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.irq_enable_interrupt_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_irq_enable_interrupt);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.irq_get_interrupt_status_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_irq_get_interrupt_status);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.irq_disable_interrupt_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_irq_disable_interrupt);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockirq_Init(void)
{
  Mockirq_Destroy();
}

void Mockirq_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void irq_register_interrupt_handler(Interrupt_IRQn n, __irq_handler h)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_irq_register_interrupt_handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_irq_register_interrupt_handler);
  cmock_call_instance = (CMOCK_irq_register_interrupt_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.irq_register_interrupt_handler_CallInstance);
  Mock.irq_register_interrupt_handler_CallInstance = CMock_Guts_MemNext(Mock.irq_register_interrupt_handler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_irq_register_interrupt_handler,CMockString_n);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_n), (void*)(&n), sizeof(Interrupt_IRQn), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_irq_register_interrupt_handler,CMockString_h);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_h), (void*)(&h), sizeof(__irq_handler), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_irq_register_interrupt_handler(CMOCK_irq_register_interrupt_handler_CALL_INSTANCE* cmock_call_instance, Interrupt_IRQn n, __irq_handler h);
void CMockExpectParameters_irq_register_interrupt_handler(CMOCK_irq_register_interrupt_handler_CALL_INSTANCE* cmock_call_instance, Interrupt_IRQn n, __irq_handler h)
{
  memcpy((void*)(&cmock_call_instance->Expected_n), (void*)(&n),
         sizeof(Interrupt_IRQn[sizeof(n) == sizeof(Interrupt_IRQn) ? 1 : -1])); /* add Interrupt_IRQn to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_h), (void*)(&h),
         sizeof(__irq_handler[sizeof(h) == sizeof(__irq_handler) ? 1 : -1])); /* add __irq_handler to :treat_as_array if this causes an error */
}

void irq_register_interrupt_handler_CMockExpect(UNITY_LINE_TYPE cmock_line, Interrupt_IRQn n, __irq_handler h)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_irq_register_interrupt_handler_CALL_INSTANCE));
  CMOCK_irq_register_interrupt_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_irq_register_interrupt_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.irq_register_interrupt_handler_CallInstance = CMock_Guts_MemChain(Mock.irq_register_interrupt_handler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_irq_register_interrupt_handler(cmock_call_instance, n, h);
}

void irq_deregister_interrupt_handler(Interrupt_IRQn n)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_irq_deregister_interrupt_handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_irq_deregister_interrupt_handler);
  cmock_call_instance = (CMOCK_irq_deregister_interrupt_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.irq_deregister_interrupt_handler_CallInstance);
  Mock.irq_deregister_interrupt_handler_CallInstance = CMock_Guts_MemNext(Mock.irq_deregister_interrupt_handler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_irq_deregister_interrupt_handler,CMockString_n);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_n), (void*)(&n), sizeof(Interrupt_IRQn), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_irq_deregister_interrupt_handler(CMOCK_irq_deregister_interrupt_handler_CALL_INSTANCE* cmock_call_instance, Interrupt_IRQn n);
void CMockExpectParameters_irq_deregister_interrupt_handler(CMOCK_irq_deregister_interrupt_handler_CALL_INSTANCE* cmock_call_instance, Interrupt_IRQn n)
{
  memcpy((void*)(&cmock_call_instance->Expected_n), (void*)(&n),
         sizeof(Interrupt_IRQn[sizeof(n) == sizeof(Interrupt_IRQn) ? 1 : -1])); /* add Interrupt_IRQn to :treat_as_array if this causes an error */
}

void irq_deregister_interrupt_handler_CMockExpect(UNITY_LINE_TYPE cmock_line, Interrupt_IRQn n)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_irq_deregister_interrupt_handler_CALL_INSTANCE));
  CMOCK_irq_deregister_interrupt_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_irq_deregister_interrupt_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.irq_deregister_interrupt_handler_CallInstance = CMock_Guts_MemChain(Mock.irq_deregister_interrupt_handler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_irq_deregister_interrupt_handler(cmock_call_instance, n);
}

void irq_register_exception_handler(Exception_IRQn n, __irq_handler h)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_irq_register_exception_handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_irq_register_exception_handler);
  cmock_call_instance = (CMOCK_irq_register_exception_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.irq_register_exception_handler_CallInstance);
  Mock.irq_register_exception_handler_CallInstance = CMock_Guts_MemNext(Mock.irq_register_exception_handler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_irq_register_exception_handler,CMockString_n);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_n), (void*)(&n), sizeof(Exception_IRQn), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_irq_register_exception_handler,CMockString_h);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_h), (void*)(&h), sizeof(__irq_handler), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_irq_register_exception_handler(CMOCK_irq_register_exception_handler_CALL_INSTANCE* cmock_call_instance, Exception_IRQn n, __irq_handler h);
void CMockExpectParameters_irq_register_exception_handler(CMOCK_irq_register_exception_handler_CALL_INSTANCE* cmock_call_instance, Exception_IRQn n, __irq_handler h)
{
  memcpy((void*)(&cmock_call_instance->Expected_n), (void*)(&n),
         sizeof(Exception_IRQn[sizeof(n) == sizeof(Exception_IRQn) ? 1 : -1])); /* add Exception_IRQn to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_h), (void*)(&h),
         sizeof(__irq_handler[sizeof(h) == sizeof(__irq_handler) ? 1 : -1])); /* add __irq_handler to :treat_as_array if this causes an error */
}

void irq_register_exception_handler_CMockExpect(UNITY_LINE_TYPE cmock_line, Exception_IRQn n, __irq_handler h)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_irq_register_exception_handler_CALL_INSTANCE));
  CMOCK_irq_register_exception_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_irq_register_exception_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.irq_register_exception_handler_CallInstance = CMock_Guts_MemChain(Mock.irq_register_exception_handler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_irq_register_exception_handler(cmock_call_instance, n, h);
}

void irq_deregister_exception_handler(Exception_IRQn n)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_irq_deregister_exception_handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_irq_deregister_exception_handler);
  cmock_call_instance = (CMOCK_irq_deregister_exception_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.irq_deregister_exception_handler_CallInstance);
  Mock.irq_deregister_exception_handler_CallInstance = CMock_Guts_MemNext(Mock.irq_deregister_exception_handler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_irq_deregister_exception_handler,CMockString_n);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_n), (void*)(&n), sizeof(Exception_IRQn), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_irq_deregister_exception_handler(CMOCK_irq_deregister_exception_handler_CALL_INSTANCE* cmock_call_instance, Exception_IRQn n);
void CMockExpectParameters_irq_deregister_exception_handler(CMOCK_irq_deregister_exception_handler_CALL_INSTANCE* cmock_call_instance, Exception_IRQn n)
{
  memcpy((void*)(&cmock_call_instance->Expected_n), (void*)(&n),
         sizeof(Exception_IRQn[sizeof(n) == sizeof(Exception_IRQn) ? 1 : -1])); /* add Exception_IRQn to :treat_as_array if this causes an error */
}

void irq_deregister_exception_handler_CMockExpect(UNITY_LINE_TYPE cmock_line, Exception_IRQn n)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_irq_deregister_exception_handler_CALL_INSTANCE));
  CMOCK_irq_deregister_exception_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_irq_deregister_exception_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.irq_deregister_exception_handler_CallInstance = CMock_Guts_MemChain(Mock.irq_deregister_exception_handler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_irq_deregister_exception_handler(cmock_call_instance, n);
}

void irq_enable_interrupt(Interrupt_IRQn irq)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_irq_enable_interrupt_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_irq_enable_interrupt);
  cmock_call_instance = (CMOCK_irq_enable_interrupt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.irq_enable_interrupt_CallInstance);
  Mock.irq_enable_interrupt_CallInstance = CMock_Guts_MemNext(Mock.irq_enable_interrupt_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_irq_enable_interrupt,CMockString_irq);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_irq), (void*)(&irq), sizeof(Interrupt_IRQn), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_irq_enable_interrupt(CMOCK_irq_enable_interrupt_CALL_INSTANCE* cmock_call_instance, Interrupt_IRQn irq);
void CMockExpectParameters_irq_enable_interrupt(CMOCK_irq_enable_interrupt_CALL_INSTANCE* cmock_call_instance, Interrupt_IRQn irq)
{
  memcpy((void*)(&cmock_call_instance->Expected_irq), (void*)(&irq),
         sizeof(Interrupt_IRQn[sizeof(irq) == sizeof(Interrupt_IRQn) ? 1 : -1])); /* add Interrupt_IRQn to :treat_as_array if this causes an error */
}

void irq_enable_interrupt_CMockExpect(UNITY_LINE_TYPE cmock_line, Interrupt_IRQn irq)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_irq_enable_interrupt_CALL_INSTANCE));
  CMOCK_irq_enable_interrupt_CALL_INSTANCE* cmock_call_instance = (CMOCK_irq_enable_interrupt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.irq_enable_interrupt_CallInstance = CMock_Guts_MemChain(Mock.irq_enable_interrupt_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_irq_enable_interrupt(cmock_call_instance, irq);
}

uint32_t irq_get_interrupt_status(Interrupt_IRQn irq)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_irq_get_interrupt_status_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_irq_get_interrupt_status);
  cmock_call_instance = (CMOCK_irq_get_interrupt_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.irq_get_interrupt_status_CallInstance);
  Mock.irq_get_interrupt_status_CallInstance = CMock_Guts_MemNext(Mock.irq_get_interrupt_status_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_irq_get_interrupt_status,CMockString_irq);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_irq), (void*)(&irq), sizeof(Interrupt_IRQn), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_irq_get_interrupt_status(CMOCK_irq_get_interrupt_status_CALL_INSTANCE* cmock_call_instance, Interrupt_IRQn irq);
void CMockExpectParameters_irq_get_interrupt_status(CMOCK_irq_get_interrupt_status_CALL_INSTANCE* cmock_call_instance, Interrupt_IRQn irq)
{
  memcpy((void*)(&cmock_call_instance->Expected_irq), (void*)(&irq),
         sizeof(Interrupt_IRQn[sizeof(irq) == sizeof(Interrupt_IRQn) ? 1 : -1])); /* add Interrupt_IRQn to :treat_as_array if this causes an error */
}

void irq_get_interrupt_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Interrupt_IRQn irq, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_irq_get_interrupt_status_CALL_INSTANCE));
  CMOCK_irq_get_interrupt_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_irq_get_interrupt_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.irq_get_interrupt_status_CallInstance = CMock_Guts_MemChain(Mock.irq_get_interrupt_status_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_irq_get_interrupt_status(cmock_call_instance, irq);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void irq_disable_interrupt(Interrupt_IRQn irq)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_irq_disable_interrupt_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_irq_disable_interrupt);
  cmock_call_instance = (CMOCK_irq_disable_interrupt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.irq_disable_interrupt_CallInstance);
  Mock.irq_disable_interrupt_CallInstance = CMock_Guts_MemNext(Mock.irq_disable_interrupt_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_irq_disable_interrupt,CMockString_irq);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_irq), (void*)(&irq), sizeof(Interrupt_IRQn), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_irq_disable_interrupt(CMOCK_irq_disable_interrupt_CALL_INSTANCE* cmock_call_instance, Interrupt_IRQn irq);
void CMockExpectParameters_irq_disable_interrupt(CMOCK_irq_disable_interrupt_CALL_INSTANCE* cmock_call_instance, Interrupt_IRQn irq)
{
  memcpy((void*)(&cmock_call_instance->Expected_irq), (void*)(&irq),
         sizeof(Interrupt_IRQn[sizeof(irq) == sizeof(Interrupt_IRQn) ? 1 : -1])); /* add Interrupt_IRQn to :treat_as_array if this causes an error */
}

void irq_disable_interrupt_CMockExpect(UNITY_LINE_TYPE cmock_line, Interrupt_IRQn irq)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_irq_disable_interrupt_CALL_INSTANCE));
  CMOCK_irq_disable_interrupt_CALL_INSTANCE* cmock_call_instance = (CMOCK_irq_disable_interrupt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.irq_disable_interrupt_CallInstance = CMock_Guts_MemChain(Mock.irq_disable_interrupt_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_irq_disable_interrupt(cmock_call_instance, irq);
}

