/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockuart_interface.h"

static const char* CMockString_apbclk = "apbclk";
static const char* CMockString_baud = "baud";
static const char* CMockString_c = "c";
static const char* CMockString_dev = "dev";
static const char* CMockString_pin_config = "pin_config";
static const char* CMockString_uart_configure_device = "uart_configure_device";
static const char* CMockString_uart_disable_device = "uart_disable_device";
static const char* CMockString_uart_enable_device = "uart_enable_device";
static const char* CMockString_uart_getc = "uart_getc";
static const char* CMockString_uart_putc = "uart_putc";
static const char* CMockString_uart_reset_device = "uart_reset_device";

typedef struct _CMOCK_uart_enable_device_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  UART_Err ReturnVal;
  UART_Device Expected_dev;
  UART_PinConfig Expected_pin_config;

} CMOCK_uart_enable_device_CALL_INSTANCE;

typedef struct _CMOCK_uart_disable_device_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  UART_Err ReturnVal;
  UART_Device Expected_dev;

} CMOCK_uart_disable_device_CALL_INSTANCE;

typedef struct _CMOCK_uart_reset_device_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  UART_Err ReturnVal;
  UART_Device Expected_dev;

} CMOCK_uart_reset_device_CALL_INSTANCE;

typedef struct _CMOCK_uart_configure_device_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  UART_Err ReturnVal;
  UART_Device Expected_dev;
  uint32_t Expected_baud;
  uint32_t Expected_apbclk;

} CMOCK_uart_configure_device_CALL_INSTANCE;

typedef struct _CMOCK_uart_putc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  UART_Device Expected_dev;
  char Expected_c;

} CMOCK_uart_putc_CALL_INSTANCE;

typedef struct _CMOCK_uart_getc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ReturnVal;
  UART_Device Expected_dev;

} CMOCK_uart_getc_CALL_INSTANCE;

static struct Mockuart_interfaceInstance
{
  CMOCK_MEM_INDEX_TYPE uart_enable_device_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_disable_device_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_reset_device_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_configure_device_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_putc_CallInstance;
  CMOCK_MEM_INDEX_TYPE uart_getc_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockuart_interface_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.uart_enable_device_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_uart_enable_device);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.uart_disable_device_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_uart_disable_device);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.uart_reset_device_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_uart_reset_device);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.uart_configure_device_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_uart_configure_device);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.uart_putc_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_uart_putc);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.uart_getc_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_uart_getc);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockuart_interface_Init(void)
{
  Mockuart_interface_Destroy();
}

void Mockuart_interface_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

UART_Err uart_enable_device(UART_Device dev, UART_PinConfig pin_config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_enable_device_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart_enable_device);
  cmock_call_instance = (CMOCK_uart_enable_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_enable_device_CallInstance);
  Mock.uart_enable_device_CallInstance = CMock_Guts_MemNext(Mock.uart_enable_device_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_uart_enable_device,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(UART_Device), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_uart_enable_device,CMockString_pin_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pin_config), (void*)(&pin_config), sizeof(UART_PinConfig), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart_enable_device(CMOCK_uart_enable_device_CALL_INSTANCE* cmock_call_instance, UART_Device dev, UART_PinConfig pin_config);
void CMockExpectParameters_uart_enable_device(CMOCK_uart_enable_device_CALL_INSTANCE* cmock_call_instance, UART_Device dev, UART_PinConfig pin_config)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(UART_Device[sizeof(dev) == sizeof(UART_Device) ? 1 : -1])); /* add UART_Device to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_pin_config), (void*)(&pin_config),
         sizeof(UART_PinConfig[sizeof(pin_config) == sizeof(UART_PinConfig) ? 1 : -1])); /* add UART_PinConfig to :treat_as_array if this causes an error */
}

void uart_enable_device_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_Device dev, UART_PinConfig pin_config, UART_Err cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_enable_device_CALL_INSTANCE));
  CMOCK_uart_enable_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_enable_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_enable_device_CallInstance = CMock_Guts_MemChain(Mock.uart_enable_device_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_enable_device(cmock_call_instance, dev, pin_config);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(UART_Err[sizeof(cmock_to_return) == sizeof(UART_Err) ? 1 : -1])); /* add UART_Err to :treat_as_array if this causes an error */
}

UART_Err uart_disable_device(UART_Device dev)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_disable_device_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart_disable_device);
  cmock_call_instance = (CMOCK_uart_disable_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_disable_device_CallInstance);
  Mock.uart_disable_device_CallInstance = CMock_Guts_MemNext(Mock.uart_disable_device_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_uart_disable_device,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(UART_Device), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart_disable_device(CMOCK_uart_disable_device_CALL_INSTANCE* cmock_call_instance, UART_Device dev);
void CMockExpectParameters_uart_disable_device(CMOCK_uart_disable_device_CALL_INSTANCE* cmock_call_instance, UART_Device dev)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(UART_Device[sizeof(dev) == sizeof(UART_Device) ? 1 : -1])); /* add UART_Device to :treat_as_array if this causes an error */
}

void uart_disable_device_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_Device dev, UART_Err cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_disable_device_CALL_INSTANCE));
  CMOCK_uart_disable_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_disable_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_disable_device_CallInstance = CMock_Guts_MemChain(Mock.uart_disable_device_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_disable_device(cmock_call_instance, dev);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(UART_Err[sizeof(cmock_to_return) == sizeof(UART_Err) ? 1 : -1])); /* add UART_Err to :treat_as_array if this causes an error */
}

UART_Err uart_reset_device(UART_Device dev)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_reset_device_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart_reset_device);
  cmock_call_instance = (CMOCK_uart_reset_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_reset_device_CallInstance);
  Mock.uart_reset_device_CallInstance = CMock_Guts_MemNext(Mock.uart_reset_device_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_uart_reset_device,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(UART_Device), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart_reset_device(CMOCK_uart_reset_device_CALL_INSTANCE* cmock_call_instance, UART_Device dev);
void CMockExpectParameters_uart_reset_device(CMOCK_uart_reset_device_CALL_INSTANCE* cmock_call_instance, UART_Device dev)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(UART_Device[sizeof(dev) == sizeof(UART_Device) ? 1 : -1])); /* add UART_Device to :treat_as_array if this causes an error */
}

void uart_reset_device_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_Device dev, UART_Err cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_reset_device_CALL_INSTANCE));
  CMOCK_uart_reset_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_reset_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_reset_device_CallInstance = CMock_Guts_MemChain(Mock.uart_reset_device_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_reset_device(cmock_call_instance, dev);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(UART_Err[sizeof(cmock_to_return) == sizeof(UART_Err) ? 1 : -1])); /* add UART_Err to :treat_as_array if this causes an error */
}

UART_Err uart_configure_device(UART_Device dev, uint32_t baud, uint32_t apbclk)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_configure_device_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart_configure_device);
  cmock_call_instance = (CMOCK_uart_configure_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_configure_device_CallInstance);
  Mock.uart_configure_device_CallInstance = CMock_Guts_MemNext(Mock.uart_configure_device_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_uart_configure_device,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(UART_Device), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_uart_configure_device,CMockString_baud);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_baud, baud, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_uart_configure_device,CMockString_apbclk);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_apbclk, apbclk, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart_configure_device(CMOCK_uart_configure_device_CALL_INSTANCE* cmock_call_instance, UART_Device dev, uint32_t baud, uint32_t apbclk);
void CMockExpectParameters_uart_configure_device(CMOCK_uart_configure_device_CALL_INSTANCE* cmock_call_instance, UART_Device dev, uint32_t baud, uint32_t apbclk)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(UART_Device[sizeof(dev) == sizeof(UART_Device) ? 1 : -1])); /* add UART_Device to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_baud = baud;
  cmock_call_instance->Expected_apbclk = apbclk;
}

void uart_configure_device_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_Device dev, uint32_t baud, uint32_t apbclk, UART_Err cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_configure_device_CALL_INSTANCE));
  CMOCK_uart_configure_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_configure_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_configure_device_CallInstance = CMock_Guts_MemChain(Mock.uart_configure_device_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_configure_device(cmock_call_instance, dev, baud, apbclk);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(UART_Err[sizeof(cmock_to_return) == sizeof(UART_Err) ? 1 : -1])); /* add UART_Err to :treat_as_array if this causes an error */
}

void uart_putc(UART_Device dev, char c)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_putc_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart_putc);
  cmock_call_instance = (CMOCK_uart_putc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_putc_CallInstance);
  Mock.uart_putc_CallInstance = CMock_Guts_MemNext(Mock.uart_putc_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_uart_putc,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(UART_Device), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_uart_putc,CMockString_c);
    UNITY_TEST_ASSERT_EQUAL_INT8(cmock_call_instance->Expected_c, c, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_uart_putc(CMOCK_uart_putc_CALL_INSTANCE* cmock_call_instance, UART_Device dev, char c);
void CMockExpectParameters_uart_putc(CMOCK_uart_putc_CALL_INSTANCE* cmock_call_instance, UART_Device dev, char c)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(UART_Device[sizeof(dev) == sizeof(UART_Device) ? 1 : -1])); /* add UART_Device to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_c = c;
}

void uart_putc_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_Device dev, char c)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_putc_CALL_INSTANCE));
  CMOCK_uart_putc_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_putc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_putc_CallInstance = CMock_Guts_MemChain(Mock.uart_putc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_putc(cmock_call_instance, dev, c);
}

char uart_getc(UART_Device dev)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uart_getc_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uart_getc);
  cmock_call_instance = (CMOCK_uart_getc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uart_getc_CallInstance);
  Mock.uart_getc_CallInstance = CMock_Guts_MemNext(Mock.uart_getc_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_uart_getc,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(UART_Device), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uart_getc(CMOCK_uart_getc_CALL_INSTANCE* cmock_call_instance, UART_Device dev);
void CMockExpectParameters_uart_getc(CMOCK_uart_getc_CALL_INSTANCE* cmock_call_instance, UART_Device dev)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(UART_Device[sizeof(dev) == sizeof(UART_Device) ? 1 : -1])); /* add UART_Device to :treat_as_array if this causes an error */
}

void uart_getc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_Device dev, char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uart_getc_CALL_INSTANCE));
  CMOCK_uart_getc_CALL_INSTANCE* cmock_call_instance = (CMOCK_uart_getc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uart_getc_CallInstance = CMock_Guts_MemChain(Mock.uart_getc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uart_getc(cmock_call_instance, dev);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

