/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockspi_interface.h"

static const char* CMockString_config = "config";
static const char* CMockString_data = "data";
static const char* CMockString_dev = "dev";
static const char* CMockString_pin_config = "pin_config";
static const char* CMockString_spi_configure_device = "spi_configure_device";
static const char* CMockString_spi_disable_device = "spi_disable_device";
static const char* CMockString_spi_enable_device = "spi_enable_device";
static const char* CMockString_spi_read = "spi_read";
static const char* CMockString_spi_reset_device = "spi_reset_device";
static const char* CMockString_spi_write = "spi_write";

typedef struct _CMOCK_spi_enable_device_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  SPI_Err ReturnVal;
  SPI_Device Expected_dev;
  SPI_PinConfig Expected_pin_config;

} CMOCK_spi_enable_device_CALL_INSTANCE;

typedef struct _CMOCK_spi_disable_device_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  SPI_Err ReturnVal;
  SPI_Device Expected_dev;

} CMOCK_spi_disable_device_CALL_INSTANCE;

typedef struct _CMOCK_spi_reset_device_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  SPI_Err ReturnVal;
  SPI_Device Expected_dev;

} CMOCK_spi_reset_device_CALL_INSTANCE;

typedef struct _CMOCK_spi_configure_device_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  SPI_Err ReturnVal;
  SPI_Device Expected_dev;
  SPI_Config Expected_config;

} CMOCK_spi_configure_device_CALL_INSTANCE;

typedef struct _CMOCK_spi_write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  SPI_Device Expected_dev;
  uint16_t Expected_data;

} CMOCK_spi_write_CALL_INSTANCE;

typedef struct _CMOCK_spi_read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  SPI_Device Expected_dev;

} CMOCK_spi_read_CALL_INSTANCE;

static struct Mockspi_interfaceInstance
{
  CMOCK_MEM_INDEX_TYPE spi_enable_device_CallInstance;
  CMOCK_MEM_INDEX_TYPE spi_disable_device_CallInstance;
  CMOCK_MEM_INDEX_TYPE spi_reset_device_CallInstance;
  CMOCK_MEM_INDEX_TYPE spi_configure_device_CallInstance;
  CMOCK_MEM_INDEX_TYPE spi_write_CallInstance;
  CMOCK_MEM_INDEX_TYPE spi_read_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockspi_interface_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.spi_enable_device_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_spi_enable_device);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.spi_disable_device_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_spi_disable_device);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.spi_reset_device_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_spi_reset_device);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.spi_configure_device_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_spi_configure_device);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.spi_write_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_spi_write);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.spi_read_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_spi_read);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockspi_interface_Init(void)
{
  Mockspi_interface_Destroy();
}

void Mockspi_interface_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

SPI_Err spi_enable_device(SPI_Device dev, SPI_PinConfig pin_config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_enable_device_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_enable_device);
  cmock_call_instance = (CMOCK_spi_enable_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_enable_device_CallInstance);
  Mock.spi_enable_device_CallInstance = CMock_Guts_MemNext(Mock.spi_enable_device_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_spi_enable_device,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(SPI_Device), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_enable_device,CMockString_pin_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pin_config), (void*)(&pin_config), sizeof(SPI_PinConfig), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_spi_enable_device(CMOCK_spi_enable_device_CALL_INSTANCE* cmock_call_instance, SPI_Device dev, SPI_PinConfig pin_config);
void CMockExpectParameters_spi_enable_device(CMOCK_spi_enable_device_CALL_INSTANCE* cmock_call_instance, SPI_Device dev, SPI_PinConfig pin_config)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(SPI_Device[sizeof(dev) == sizeof(SPI_Device) ? 1 : -1])); /* add SPI_Device to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_pin_config), (void*)(&pin_config),
         sizeof(SPI_PinConfig[sizeof(pin_config) == sizeof(SPI_PinConfig) ? 1 : -1])); /* add SPI_PinConfig to :treat_as_array if this causes an error */
}

void spi_enable_device_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_Device dev, SPI_PinConfig pin_config, SPI_Err cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_enable_device_CALL_INSTANCE));
  CMOCK_spi_enable_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_enable_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_enable_device_CallInstance = CMock_Guts_MemChain(Mock.spi_enable_device_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spi_enable_device(cmock_call_instance, dev, pin_config);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(SPI_Err[sizeof(cmock_to_return) == sizeof(SPI_Err) ? 1 : -1])); /* add SPI_Err to :treat_as_array if this causes an error */
}

SPI_Err spi_disable_device(SPI_Device dev)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_disable_device_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_disable_device);
  cmock_call_instance = (CMOCK_spi_disable_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_disable_device_CallInstance);
  Mock.spi_disable_device_CallInstance = CMock_Guts_MemNext(Mock.spi_disable_device_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_spi_disable_device,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(SPI_Device), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_spi_disable_device(CMOCK_spi_disable_device_CALL_INSTANCE* cmock_call_instance, SPI_Device dev);
void CMockExpectParameters_spi_disable_device(CMOCK_spi_disable_device_CALL_INSTANCE* cmock_call_instance, SPI_Device dev)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(SPI_Device[sizeof(dev) == sizeof(SPI_Device) ? 1 : -1])); /* add SPI_Device to :treat_as_array if this causes an error */
}

void spi_disable_device_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_Device dev, SPI_Err cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_disable_device_CALL_INSTANCE));
  CMOCK_spi_disable_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_disable_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_disable_device_CallInstance = CMock_Guts_MemChain(Mock.spi_disable_device_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spi_disable_device(cmock_call_instance, dev);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(SPI_Err[sizeof(cmock_to_return) == sizeof(SPI_Err) ? 1 : -1])); /* add SPI_Err to :treat_as_array if this causes an error */
}

SPI_Err spi_reset_device(SPI_Device dev)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_reset_device_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_reset_device);
  cmock_call_instance = (CMOCK_spi_reset_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_reset_device_CallInstance);
  Mock.spi_reset_device_CallInstance = CMock_Guts_MemNext(Mock.spi_reset_device_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_spi_reset_device,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(SPI_Device), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_spi_reset_device(CMOCK_spi_reset_device_CALL_INSTANCE* cmock_call_instance, SPI_Device dev);
void CMockExpectParameters_spi_reset_device(CMOCK_spi_reset_device_CALL_INSTANCE* cmock_call_instance, SPI_Device dev)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(SPI_Device[sizeof(dev) == sizeof(SPI_Device) ? 1 : -1])); /* add SPI_Device to :treat_as_array if this causes an error */
}

void spi_reset_device_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_Device dev, SPI_Err cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_reset_device_CALL_INSTANCE));
  CMOCK_spi_reset_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_reset_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_reset_device_CallInstance = CMock_Guts_MemChain(Mock.spi_reset_device_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spi_reset_device(cmock_call_instance, dev);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(SPI_Err[sizeof(cmock_to_return) == sizeof(SPI_Err) ? 1 : -1])); /* add SPI_Err to :treat_as_array if this causes an error */
}

SPI_Err spi_configure_device(SPI_Device dev, SPI_Config config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_configure_device_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_configure_device);
  cmock_call_instance = (CMOCK_spi_configure_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_configure_device_CallInstance);
  Mock.spi_configure_device_CallInstance = CMock_Guts_MemNext(Mock.spi_configure_device_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_spi_configure_device,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(SPI_Device), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_configure_device,CMockString_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_config), (void*)(&config), sizeof(SPI_Config), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_spi_configure_device(CMOCK_spi_configure_device_CALL_INSTANCE* cmock_call_instance, SPI_Device dev, SPI_Config config);
void CMockExpectParameters_spi_configure_device(CMOCK_spi_configure_device_CALL_INSTANCE* cmock_call_instance, SPI_Device dev, SPI_Config config)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(SPI_Device[sizeof(dev) == sizeof(SPI_Device) ? 1 : -1])); /* add SPI_Device to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_config), (void*)(&config),
         sizeof(SPI_Config[sizeof(config) == sizeof(SPI_Config) ? 1 : -1])); /* add SPI_Config to :treat_as_array if this causes an error */
}

void spi_configure_device_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_Device dev, SPI_Config config, SPI_Err cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_configure_device_CALL_INSTANCE));
  CMOCK_spi_configure_device_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_configure_device_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_configure_device_CallInstance = CMock_Guts_MemChain(Mock.spi_configure_device_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spi_configure_device(cmock_call_instance, dev, config);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(SPI_Err[sizeof(cmock_to_return) == sizeof(SPI_Err) ? 1 : -1])); /* add SPI_Err to :treat_as_array if this causes an error */
}

void spi_write(SPI_Device dev, uint16_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_write_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_write);
  cmock_call_instance = (CMOCK_spi_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_write_CallInstance);
  Mock.spi_write_CallInstance = CMock_Guts_MemNext(Mock.spi_write_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_spi_write,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(SPI_Device), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_write,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_spi_write(CMOCK_spi_write_CALL_INSTANCE* cmock_call_instance, SPI_Device dev, uint16_t data);
void CMockExpectParameters_spi_write(CMOCK_spi_write_CALL_INSTANCE* cmock_call_instance, SPI_Device dev, uint16_t data)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(SPI_Device[sizeof(dev) == sizeof(SPI_Device) ? 1 : -1])); /* add SPI_Device to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void spi_write_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_Device dev, uint16_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_write_CALL_INSTANCE));
  CMOCK_spi_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_write_CallInstance = CMock_Guts_MemChain(Mock.spi_write_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spi_write(cmock_call_instance, dev, data);
}

uint16_t spi_read(SPI_Device dev)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_read);
  cmock_call_instance = (CMOCK_spi_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_read_CallInstance);
  Mock.spi_read_CallInstance = CMock_Guts_MemNext(Mock.spi_read_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_spi_read,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev), sizeof(SPI_Device), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_spi_read(CMOCK_spi_read_CALL_INSTANCE* cmock_call_instance, SPI_Device dev);
void CMockExpectParameters_spi_read(CMOCK_spi_read_CALL_INSTANCE* cmock_call_instance, SPI_Device dev)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev), (void*)(&dev),
         sizeof(SPI_Device[sizeof(dev) == sizeof(SPI_Device) ? 1 : -1])); /* add SPI_Device to :treat_as_array if this causes an error */
}

void spi_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_Device dev, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_read_CALL_INSTANCE));
  CMOCK_spi_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_read_CallInstance = CMock_Guts_MemChain(Mock.spi_read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spi_read(cmock_call_instance, dev);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

