/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockgpio_interface.h"

static const char* CMockString_config = "config";
static const char* CMockString_gpio_lock_pin = "gpio_lock_pin";
static const char* CMockString_gpio_pin_config = "gpio_pin_config";
static const char* CMockString_gpio_pin_input = "gpio_pin_input";
static const char* CMockString_gpio_pin_output = "gpio_pin_output";
static const char* CMockString_gpio_pin_pullstate_config = "gpio_pin_pullstate_config";
static const char* CMockString_gpio_port_disable = "gpio_port_disable";
static const char* CMockString_gpio_port_enable = "gpio_port_enable";
static const char* CMockString_gpio_unlock_pin = "gpio_unlock_pin";
static const char* CMockString_mode = "mode";
static const char* CMockString_pin = "pin";
static const char* CMockString_port = "port";
static const char* CMockString_rcc_devid = "rcc_devid";
static const char* CMockString_state = "state";

typedef struct _CMOCK_gpio_port_enable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GPIO_Port Expected_port;

} CMOCK_gpio_port_enable_CALL_INSTANCE;

typedef struct _CMOCK_gpio_port_disable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GPIO_Port Expected_port;

} CMOCK_gpio_port_disable_CALL_INSTANCE;

typedef struct _CMOCK_gpio_lock_pin_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GPIO_Err ReturnVal;
  RCC_DevId Expected_rcc_devid;
  GPIO_Pin Expected_pin;

} CMOCK_gpio_lock_pin_CALL_INSTANCE;

typedef struct _CMOCK_gpio_unlock_pin_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GPIO_Err ReturnVal;
  RCC_DevId Expected_rcc_devid;
  GPIO_Pin Expected_pin;

} CMOCK_gpio_unlock_pin_CALL_INSTANCE;

typedef struct _CMOCK_gpio_pin_config_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GPIO_Pin Expected_pin;
  GPIO_Mode Expected_mode;
  GPIO_Config Expected_config;

} CMOCK_gpio_pin_config_CALL_INSTANCE;

typedef struct _CMOCK_gpio_pin_pullstate_config_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GPIO_Pin Expected_pin;
  GPIO_PullState Expected_state;

} CMOCK_gpio_pin_pullstate_config_CALL_INSTANCE;

typedef struct _CMOCK_gpio_pin_input_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GPIO_State ReturnVal;
  GPIO_Pin Expected_pin;

} CMOCK_gpio_pin_input_CALL_INSTANCE;

typedef struct _CMOCK_gpio_pin_output_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GPIO_Pin Expected_pin;
  GPIO_State Expected_state;

} CMOCK_gpio_pin_output_CALL_INSTANCE;

static struct Mockgpio_interfaceInstance
{
  CMOCK_MEM_INDEX_TYPE gpio_port_enable_CallInstance;
  CMOCK_MEM_INDEX_TYPE gpio_port_disable_CallInstance;
  CMOCK_MEM_INDEX_TYPE gpio_lock_pin_CallInstance;
  CMOCK_MEM_INDEX_TYPE gpio_unlock_pin_CallInstance;
  CMOCK_MEM_INDEX_TYPE gpio_pin_config_CallInstance;
  CMOCK_MEM_INDEX_TYPE gpio_pin_pullstate_config_CallInstance;
  CMOCK_MEM_INDEX_TYPE gpio_pin_input_CallInstance;
  CMOCK_MEM_INDEX_TYPE gpio_pin_output_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockgpio_interface_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.gpio_port_enable_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_port_enable);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.gpio_port_disable_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_port_disable);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.gpio_lock_pin_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_lock_pin);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.gpio_unlock_pin_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_unlock_pin);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.gpio_pin_config_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_pin_config);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.gpio_pin_pullstate_config_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_pin_pullstate_config);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.gpio_pin_input_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_pin_input);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.gpio_pin_output_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_gpio_pin_output);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockgpio_interface_Init(void)
{
  Mockgpio_interface_Destroy();
}

void Mockgpio_interface_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void gpio_port_enable(GPIO_Port port)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_port_enable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_port_enable);
  cmock_call_instance = (CMOCK_gpio_port_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_port_enable_CallInstance);
  Mock.gpio_port_enable_CallInstance = CMock_Guts_MemNext(Mock.gpio_port_enable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_gpio_port_enable,CMockString_port);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_port), (void*)(&port), sizeof(GPIO_Port), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_gpio_port_enable(CMOCK_gpio_port_enable_CALL_INSTANCE* cmock_call_instance, GPIO_Port port);
void CMockExpectParameters_gpio_port_enable(CMOCK_gpio_port_enable_CALL_INSTANCE* cmock_call_instance, GPIO_Port port)
{
  memcpy((void*)(&cmock_call_instance->Expected_port), (void*)(&port),
         sizeof(GPIO_Port[sizeof(port) == sizeof(GPIO_Port) ? 1 : -1])); /* add GPIO_Port to :treat_as_array if this causes an error */
}

void gpio_port_enable_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_Port port)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_port_enable_CALL_INSTANCE));
  CMOCK_gpio_port_enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_port_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_port_enable_CallInstance = CMock_Guts_MemChain(Mock.gpio_port_enable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_gpio_port_enable(cmock_call_instance, port);
}

void gpio_port_disable(GPIO_Port port)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_port_disable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_port_disable);
  cmock_call_instance = (CMOCK_gpio_port_disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_port_disable_CallInstance);
  Mock.gpio_port_disable_CallInstance = CMock_Guts_MemNext(Mock.gpio_port_disable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_gpio_port_disable,CMockString_port);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_port), (void*)(&port), sizeof(GPIO_Port), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_gpio_port_disable(CMOCK_gpio_port_disable_CALL_INSTANCE* cmock_call_instance, GPIO_Port port);
void CMockExpectParameters_gpio_port_disable(CMOCK_gpio_port_disable_CALL_INSTANCE* cmock_call_instance, GPIO_Port port)
{
  memcpy((void*)(&cmock_call_instance->Expected_port), (void*)(&port),
         sizeof(GPIO_Port[sizeof(port) == sizeof(GPIO_Port) ? 1 : -1])); /* add GPIO_Port to :treat_as_array if this causes an error */
}

void gpio_port_disable_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_Port port)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_port_disable_CALL_INSTANCE));
  CMOCK_gpio_port_disable_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_port_disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_port_disable_CallInstance = CMock_Guts_MemChain(Mock.gpio_port_disable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_gpio_port_disable(cmock_call_instance, port);
}

GPIO_Err gpio_lock_pin(RCC_DevId rcc_devid, GPIO_Pin pin)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_lock_pin_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_lock_pin);
  cmock_call_instance = (CMOCK_gpio_lock_pin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_lock_pin_CallInstance);
  Mock.gpio_lock_pin_CallInstance = CMock_Guts_MemNext(Mock.gpio_lock_pin_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_gpio_lock_pin,CMockString_rcc_devid);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_rcc_devid), (void*)(&rcc_devid), sizeof(RCC_DevId), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_gpio_lock_pin,CMockString_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin), sizeof(GPIO_Pin), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_gpio_lock_pin(CMOCK_gpio_lock_pin_CALL_INSTANCE* cmock_call_instance, RCC_DevId rcc_devid, GPIO_Pin pin);
void CMockExpectParameters_gpio_lock_pin(CMOCK_gpio_lock_pin_CALL_INSTANCE* cmock_call_instance, RCC_DevId rcc_devid, GPIO_Pin pin)
{
  memcpy((void*)(&cmock_call_instance->Expected_rcc_devid), (void*)(&rcc_devid),
         sizeof(RCC_DevId[sizeof(rcc_devid) == sizeof(RCC_DevId) ? 1 : -1])); /* add RCC_DevId to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin),
         sizeof(GPIO_Pin[sizeof(pin) == sizeof(GPIO_Pin) ? 1 : -1])); /* add GPIO_Pin to :treat_as_array if this causes an error */
}

void gpio_lock_pin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RCC_DevId rcc_devid, GPIO_Pin pin, GPIO_Err cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_lock_pin_CALL_INSTANCE));
  CMOCK_gpio_lock_pin_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_lock_pin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_lock_pin_CallInstance = CMock_Guts_MemChain(Mock.gpio_lock_pin_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_gpio_lock_pin(cmock_call_instance, rcc_devid, pin);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(GPIO_Err[sizeof(cmock_to_return) == sizeof(GPIO_Err) ? 1 : -1])); /* add GPIO_Err to :treat_as_array if this causes an error */
}

GPIO_Err gpio_unlock_pin(RCC_DevId rcc_devid, GPIO_Pin pin)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_unlock_pin_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_unlock_pin);
  cmock_call_instance = (CMOCK_gpio_unlock_pin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_unlock_pin_CallInstance);
  Mock.gpio_unlock_pin_CallInstance = CMock_Guts_MemNext(Mock.gpio_unlock_pin_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_gpio_unlock_pin,CMockString_rcc_devid);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_rcc_devid), (void*)(&rcc_devid), sizeof(RCC_DevId), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_gpio_unlock_pin,CMockString_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin), sizeof(GPIO_Pin), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_gpio_unlock_pin(CMOCK_gpio_unlock_pin_CALL_INSTANCE* cmock_call_instance, RCC_DevId rcc_devid, GPIO_Pin pin);
void CMockExpectParameters_gpio_unlock_pin(CMOCK_gpio_unlock_pin_CALL_INSTANCE* cmock_call_instance, RCC_DevId rcc_devid, GPIO_Pin pin)
{
  memcpy((void*)(&cmock_call_instance->Expected_rcc_devid), (void*)(&rcc_devid),
         sizeof(RCC_DevId[sizeof(rcc_devid) == sizeof(RCC_DevId) ? 1 : -1])); /* add RCC_DevId to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin),
         sizeof(GPIO_Pin[sizeof(pin) == sizeof(GPIO_Pin) ? 1 : -1])); /* add GPIO_Pin to :treat_as_array if this causes an error */
}

void gpio_unlock_pin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RCC_DevId rcc_devid, GPIO_Pin pin, GPIO_Err cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_unlock_pin_CALL_INSTANCE));
  CMOCK_gpio_unlock_pin_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_unlock_pin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_unlock_pin_CallInstance = CMock_Guts_MemChain(Mock.gpio_unlock_pin_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_gpio_unlock_pin(cmock_call_instance, rcc_devid, pin);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(GPIO_Err[sizeof(cmock_to_return) == sizeof(GPIO_Err) ? 1 : -1])); /* add GPIO_Err to :treat_as_array if this causes an error */
}

void gpio_pin_config(GPIO_Pin pin, GPIO_Mode mode, GPIO_Config config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_pin_config_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_pin_config);
  cmock_call_instance = (CMOCK_gpio_pin_config_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_pin_config_CallInstance);
  Mock.gpio_pin_config_CallInstance = CMock_Guts_MemNext(Mock.gpio_pin_config_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_gpio_pin_config,CMockString_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin), sizeof(GPIO_Pin), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_gpio_pin_config,CMockString_mode);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_mode), (void*)(&mode), sizeof(GPIO_Mode), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_gpio_pin_config,CMockString_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_config), (void*)(&config), sizeof(GPIO_Config), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_gpio_pin_config(CMOCK_gpio_pin_config_CALL_INSTANCE* cmock_call_instance, GPIO_Pin pin, GPIO_Mode mode, GPIO_Config config);
void CMockExpectParameters_gpio_pin_config(CMOCK_gpio_pin_config_CALL_INSTANCE* cmock_call_instance, GPIO_Pin pin, GPIO_Mode mode, GPIO_Config config)
{
  memcpy((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin),
         sizeof(GPIO_Pin[sizeof(pin) == sizeof(GPIO_Pin) ? 1 : -1])); /* add GPIO_Pin to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_mode), (void*)(&mode),
         sizeof(GPIO_Mode[sizeof(mode) == sizeof(GPIO_Mode) ? 1 : -1])); /* add GPIO_Mode to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_config), (void*)(&config),
         sizeof(GPIO_Config[sizeof(config) == sizeof(GPIO_Config) ? 1 : -1])); /* add GPIO_Config to :treat_as_array if this causes an error */
}

void gpio_pin_config_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_Pin pin, GPIO_Mode mode, GPIO_Config config)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_pin_config_CALL_INSTANCE));
  CMOCK_gpio_pin_config_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_pin_config_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_pin_config_CallInstance = CMock_Guts_MemChain(Mock.gpio_pin_config_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_gpio_pin_config(cmock_call_instance, pin, mode, config);
}

void gpio_pin_pullstate_config(GPIO_Pin pin, GPIO_PullState state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_pin_pullstate_config_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_pin_pullstate_config);
  cmock_call_instance = (CMOCK_gpio_pin_pullstate_config_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_pin_pullstate_config_CallInstance);
  Mock.gpio_pin_pullstate_config_CallInstance = CMock_Guts_MemNext(Mock.gpio_pin_pullstate_config_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_gpio_pin_pullstate_config,CMockString_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin), sizeof(GPIO_Pin), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_gpio_pin_pullstate_config,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(GPIO_PullState), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_gpio_pin_pullstate_config(CMOCK_gpio_pin_pullstate_config_CALL_INSTANCE* cmock_call_instance, GPIO_Pin pin, GPIO_PullState state);
void CMockExpectParameters_gpio_pin_pullstate_config(CMOCK_gpio_pin_pullstate_config_CALL_INSTANCE* cmock_call_instance, GPIO_Pin pin, GPIO_PullState state)
{
  memcpy((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin),
         sizeof(GPIO_Pin[sizeof(pin) == sizeof(GPIO_Pin) ? 1 : -1])); /* add GPIO_Pin to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_state), (void*)(&state),
         sizeof(GPIO_PullState[sizeof(state) == sizeof(GPIO_PullState) ? 1 : -1])); /* add GPIO_PullState to :treat_as_array if this causes an error */
}

void gpio_pin_pullstate_config_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_Pin pin, GPIO_PullState state)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_pin_pullstate_config_CALL_INSTANCE));
  CMOCK_gpio_pin_pullstate_config_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_pin_pullstate_config_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_pin_pullstate_config_CallInstance = CMock_Guts_MemChain(Mock.gpio_pin_pullstate_config_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_gpio_pin_pullstate_config(cmock_call_instance, pin, state);
}

GPIO_State gpio_pin_input(GPIO_Pin pin)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_pin_input_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_pin_input);
  cmock_call_instance = (CMOCK_gpio_pin_input_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_pin_input_CallInstance);
  Mock.gpio_pin_input_CallInstance = CMock_Guts_MemNext(Mock.gpio_pin_input_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_gpio_pin_input,CMockString_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin), sizeof(GPIO_Pin), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_gpio_pin_input(CMOCK_gpio_pin_input_CALL_INSTANCE* cmock_call_instance, GPIO_Pin pin);
void CMockExpectParameters_gpio_pin_input(CMOCK_gpio_pin_input_CALL_INSTANCE* cmock_call_instance, GPIO_Pin pin)
{
  memcpy((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin),
         sizeof(GPIO_Pin[sizeof(pin) == sizeof(GPIO_Pin) ? 1 : -1])); /* add GPIO_Pin to :treat_as_array if this causes an error */
}

void gpio_pin_input_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GPIO_Pin pin, GPIO_State cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_pin_input_CALL_INSTANCE));
  CMOCK_gpio_pin_input_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_pin_input_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_pin_input_CallInstance = CMock_Guts_MemChain(Mock.gpio_pin_input_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_gpio_pin_input(cmock_call_instance, pin);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(GPIO_State[sizeof(cmock_to_return) == sizeof(GPIO_State) ? 1 : -1])); /* add GPIO_State to :treat_as_array if this causes an error */
}

void gpio_pin_output(GPIO_Pin pin, GPIO_State state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_gpio_pin_output_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_gpio_pin_output);
  cmock_call_instance = (CMOCK_gpio_pin_output_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.gpio_pin_output_CallInstance);
  Mock.gpio_pin_output_CallInstance = CMock_Guts_MemNext(Mock.gpio_pin_output_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_gpio_pin_output,CMockString_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin), sizeof(GPIO_Pin), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_gpio_pin_output,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(GPIO_State), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_gpio_pin_output(CMOCK_gpio_pin_output_CALL_INSTANCE* cmock_call_instance, GPIO_Pin pin, GPIO_State state);
void CMockExpectParameters_gpio_pin_output(CMOCK_gpio_pin_output_CALL_INSTANCE* cmock_call_instance, GPIO_Pin pin, GPIO_State state)
{
  memcpy((void*)(&cmock_call_instance->Expected_pin), (void*)(&pin),
         sizeof(GPIO_Pin[sizeof(pin) == sizeof(GPIO_Pin) ? 1 : -1])); /* add GPIO_Pin to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_state), (void*)(&state),
         sizeof(GPIO_State[sizeof(state) == sizeof(GPIO_State) ? 1 : -1])); /* add GPIO_State to :treat_as_array if this causes an error */
}

void gpio_pin_output_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_Pin pin, GPIO_State state)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_gpio_pin_output_CALL_INSTANCE));
  CMOCK_gpio_pin_output_CALL_INSTANCE* cmock_call_instance = (CMOCK_gpio_pin_output_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.gpio_pin_output_CallInstance = CMock_Guts_MemChain(Mock.gpio_pin_output_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_gpio_pin_output(cmock_call_instance, pin, state);
}

