/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocktime.h"

static const char* CMockString_ms = "ms";
static const char* CMockString_mul = "mul";
static const char* CMockString_system_pll_clock_init = "system_pll_clock_init";
static const char* CMockString_us = "us";
static const char* CMockString_wait_ms = "wait_ms";
static const char* CMockString_wait_us = "wait_us";

typedef struct _CMOCK_wait_ms_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_ms;

} CMOCK_wait_ms_CALL_INSTANCE;

typedef struct _CMOCK_wait_us_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_us;

} CMOCK_wait_us_CALL_INSTANCE;

typedef struct _CMOCK_system_pll_clock_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  PLLMul Expected_mul;

} CMOCK_system_pll_clock_init_CALL_INSTANCE;

static struct MocktimeInstance
{
  CMOCK_MEM_INDEX_TYPE wait_ms_CallInstance;
  CMOCK_MEM_INDEX_TYPE wait_us_CallInstance;
  CMOCK_MEM_INDEX_TYPE system_pll_clock_init_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocktime_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.wait_ms_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wait_ms);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wait_us_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wait_us);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.system_pll_clock_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_system_pll_clock_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mocktime_Init(void)
{
  Mocktime_Destroy();
}

void Mocktime_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void wait_ms(uint32_t ms)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wait_ms_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wait_ms);
  cmock_call_instance = (CMOCK_wait_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wait_ms_CallInstance);
  Mock.wait_ms_CallInstance = CMock_Guts_MemNext(Mock.wait_ms_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wait_ms,CMockString_ms);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ms, ms, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_wait_ms(CMOCK_wait_ms_CALL_INSTANCE* cmock_call_instance, uint32_t ms);
void CMockExpectParameters_wait_ms(CMOCK_wait_ms_CALL_INSTANCE* cmock_call_instance, uint32_t ms)
{
  cmock_call_instance->Expected_ms = ms;
}

void wait_ms_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ms)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wait_ms_CALL_INSTANCE));
  CMOCK_wait_ms_CALL_INSTANCE* cmock_call_instance = (CMOCK_wait_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wait_ms_CallInstance = CMock_Guts_MemChain(Mock.wait_ms_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wait_ms(cmock_call_instance, ms);
}

void wait_us(uint32_t us)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wait_us_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wait_us);
  cmock_call_instance = (CMOCK_wait_us_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wait_us_CallInstance);
  Mock.wait_us_CallInstance = CMock_Guts_MemNext(Mock.wait_us_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wait_us,CMockString_us);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_us, us, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_wait_us(CMOCK_wait_us_CALL_INSTANCE* cmock_call_instance, uint32_t us);
void CMockExpectParameters_wait_us(CMOCK_wait_us_CALL_INSTANCE* cmock_call_instance, uint32_t us)
{
  cmock_call_instance->Expected_us = us;
}

void wait_us_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t us)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wait_us_CALL_INSTANCE));
  CMOCK_wait_us_CALL_INSTANCE* cmock_call_instance = (CMOCK_wait_us_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wait_us_CallInstance = CMock_Guts_MemChain(Mock.wait_us_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wait_us(cmock_call_instance, us);
}

void system_pll_clock_init(PLLMul mul)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_system_pll_clock_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_system_pll_clock_init);
  cmock_call_instance = (CMOCK_system_pll_clock_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.system_pll_clock_init_CallInstance);
  Mock.system_pll_clock_init_CallInstance = CMock_Guts_MemNext(Mock.system_pll_clock_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_system_pll_clock_init,CMockString_mul);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_mul), (void*)(&mul), sizeof(PLLMul), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_system_pll_clock_init(CMOCK_system_pll_clock_init_CALL_INSTANCE* cmock_call_instance, PLLMul mul);
void CMockExpectParameters_system_pll_clock_init(CMOCK_system_pll_clock_init_CALL_INSTANCE* cmock_call_instance, PLLMul mul)
{
  memcpy((void*)(&cmock_call_instance->Expected_mul), (void*)(&mul),
         sizeof(PLLMul[sizeof(mul) == sizeof(PLLMul) ? 1 : -1])); /* add PLLMul to :treat_as_array if this causes an error */
}

void system_pll_clock_init_CMockExpect(UNITY_LINE_TYPE cmock_line, PLLMul mul)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_system_pll_clock_init_CALL_INSTANCE));
  CMOCK_system_pll_clock_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_system_pll_clock_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.system_pll_clock_init_CallInstance = CMock_Guts_MemChain(Mock.system_pll_clock_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_system_pll_clock_init(cmock_call_instance, mul);
}

