/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmmio_ops.h"

static const char* CMockString_base = "base";
static const char* CMockString_data = "data";
static const char* CMockString_mask = "mask";
static const char* CMockString_mmio_and_readb = "mmio_and_readb";
static const char* CMockString_mmio_and_readdw = "mmio_and_readdw";
static const char* CMockString_mmio_and_readw = "mmio_and_readw";
static const char* CMockString_mmio_and_writeb = "mmio_and_writeb";
static const char* CMockString_mmio_and_writedw = "mmio_and_writedw";
static const char* CMockString_mmio_and_writew = "mmio_and_writew";
static const char* CMockString_mmio_or_writeb = "mmio_or_writeb";
static const char* CMockString_mmio_or_writedw = "mmio_or_writedw";
static const char* CMockString_mmio_or_writew = "mmio_or_writew";
static const char* CMockString_mmio_readb = "mmio_readb";
static const char* CMockString_mmio_readdw = "mmio_readdw";
static const char* CMockString_mmio_readw = "mmio_readw";
static const char* CMockString_mmio_writeb = "mmio_writeb";
static const char* CMockString_mmio_writedw = "mmio_writedw";
static const char* CMockString_mmio_writew = "mmio_writew";

typedef struct _CMOCK_mmio_or_writeb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uintptr_t Expected_base;
  uint8_t Expected_data;

} CMOCK_mmio_or_writeb_CALL_INSTANCE;

typedef struct _CMOCK_mmio_or_writew_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uintptr_t Expected_base;
  uint16_t Expected_data;

} CMOCK_mmio_or_writew_CALL_INSTANCE;

typedef struct _CMOCK_mmio_or_writedw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uintptr_t Expected_base;
  uint32_t Expected_data;

} CMOCK_mmio_or_writedw_CALL_INSTANCE;

typedef struct _CMOCK_mmio_and_writeb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uintptr_t Expected_base;
  uint8_t Expected_data;

} CMOCK_mmio_and_writeb_CALL_INSTANCE;

typedef struct _CMOCK_mmio_and_writew_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uintptr_t Expected_base;
  uint16_t Expected_data;

} CMOCK_mmio_and_writew_CALL_INSTANCE;

typedef struct _CMOCK_mmio_and_writedw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uintptr_t Expected_base;
  uint32_t Expected_data;

} CMOCK_mmio_and_writedw_CALL_INSTANCE;

typedef struct _CMOCK_mmio_writeb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uintptr_t Expected_base;
  uint8_t Expected_data;

} CMOCK_mmio_writeb_CALL_INSTANCE;

typedef struct _CMOCK_mmio_writew_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uintptr_t Expected_base;
  uint16_t Expected_data;

} CMOCK_mmio_writew_CALL_INSTANCE;

typedef struct _CMOCK_mmio_writedw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uintptr_t Expected_base;
  uint32_t Expected_data;

} CMOCK_mmio_writedw_CALL_INSTANCE;

typedef struct _CMOCK_mmio_readb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  uintptr_t Expected_base;

} CMOCK_mmio_readb_CALL_INSTANCE;

typedef struct _CMOCK_mmio_readw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  uintptr_t Expected_base;

} CMOCK_mmio_readw_CALL_INSTANCE;

typedef struct _CMOCK_mmio_readdw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  uintptr_t Expected_base;

} CMOCK_mmio_readdw_CALL_INSTANCE;

typedef struct _CMOCK_mmio_and_readb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  uintptr_t Expected_base;
  uint8_t Expected_mask;

} CMOCK_mmio_and_readb_CALL_INSTANCE;

typedef struct _CMOCK_mmio_and_readw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  uintptr_t Expected_base;
  uint16_t Expected_mask;

} CMOCK_mmio_and_readw_CALL_INSTANCE;

typedef struct _CMOCK_mmio_and_readdw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  uintptr_t Expected_base;
  uint32_t Expected_mask;

} CMOCK_mmio_and_readdw_CALL_INSTANCE;

static struct Mockmmio_opsInstance
{
  CMOCK_MEM_INDEX_TYPE mmio_or_writeb_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_or_writew_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_or_writedw_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_and_writeb_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_and_writew_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_and_writedw_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_writeb_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_writew_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_writedw_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_readb_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_readw_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_readdw_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_and_readb_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_and_readw_CallInstance;
  CMOCK_MEM_INDEX_TYPE mmio_and_readdw_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmmio_ops_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.mmio_or_writeb_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_or_writeb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_or_writew_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_or_writew);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_or_writedw_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_or_writedw);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_and_writeb_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_and_writeb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_and_writew_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_and_writew);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_and_writedw_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_and_writedw);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_writeb_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_writeb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_writew_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_writew);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_writedw_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_writedw);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_readb_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_readb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_readw_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_readw);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_readdw_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_readdw);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_and_readb_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_and_readb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_and_readw_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_and_readw);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.mmio_and_readdw_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mmio_and_readdw);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockmmio_ops_Init(void)
{
  Mockmmio_ops_Destroy();
}

void Mockmmio_ops_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void mmio_or_writeb(uintptr_t base, uint8_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_or_writeb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_or_writeb);
  cmock_call_instance = (CMOCK_mmio_or_writeb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_or_writeb_CallInstance);
  Mock.mmio_or_writeb_CallInstance = CMock_Guts_MemNext(Mock.mmio_or_writeb_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_or_writeb,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_or_writeb,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_mmio_or_writeb(CMOCK_mmio_or_writeb_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint8_t data);
void CMockExpectParameters_mmio_or_writeb(CMOCK_mmio_or_writeb_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint8_t data)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void mmio_or_writeb_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint8_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_or_writeb_CALL_INSTANCE));
  CMOCK_mmio_or_writeb_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_or_writeb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_or_writeb_CallInstance = CMock_Guts_MemChain(Mock.mmio_or_writeb_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_or_writeb(cmock_call_instance, base, data);
}

void mmio_or_writew(uintptr_t base, uint16_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_or_writew_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_or_writew);
  cmock_call_instance = (CMOCK_mmio_or_writew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_or_writew_CallInstance);
  Mock.mmio_or_writew_CallInstance = CMock_Guts_MemNext(Mock.mmio_or_writew_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_or_writew,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_or_writew,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_mmio_or_writew(CMOCK_mmio_or_writew_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint16_t data);
void CMockExpectParameters_mmio_or_writew(CMOCK_mmio_or_writew_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint16_t data)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void mmio_or_writew_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint16_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_or_writew_CALL_INSTANCE));
  CMOCK_mmio_or_writew_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_or_writew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_or_writew_CallInstance = CMock_Guts_MemChain(Mock.mmio_or_writew_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_or_writew(cmock_call_instance, base, data);
}

void mmio_or_writedw(uintptr_t base, uint32_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_or_writedw_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_or_writedw);
  cmock_call_instance = (CMOCK_mmio_or_writedw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_or_writedw_CallInstance);
  Mock.mmio_or_writedw_CallInstance = CMock_Guts_MemNext(Mock.mmio_or_writedw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_or_writedw,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_or_writedw,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_mmio_or_writedw(CMOCK_mmio_or_writedw_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint32_t data);
void CMockExpectParameters_mmio_or_writedw(CMOCK_mmio_or_writedw_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint32_t data)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void mmio_or_writedw_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint32_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_or_writedw_CALL_INSTANCE));
  CMOCK_mmio_or_writedw_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_or_writedw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_or_writedw_CallInstance = CMock_Guts_MemChain(Mock.mmio_or_writedw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_or_writedw(cmock_call_instance, base, data);
}

void mmio_and_writeb(uintptr_t base, uint8_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_and_writeb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_and_writeb);
  cmock_call_instance = (CMOCK_mmio_and_writeb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_and_writeb_CallInstance);
  Mock.mmio_and_writeb_CallInstance = CMock_Guts_MemNext(Mock.mmio_and_writeb_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_writeb,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_writeb,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_mmio_and_writeb(CMOCK_mmio_and_writeb_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint8_t data);
void CMockExpectParameters_mmio_and_writeb(CMOCK_mmio_and_writeb_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint8_t data)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void mmio_and_writeb_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint8_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_and_writeb_CALL_INSTANCE));
  CMOCK_mmio_and_writeb_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_and_writeb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_and_writeb_CallInstance = CMock_Guts_MemChain(Mock.mmio_and_writeb_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_and_writeb(cmock_call_instance, base, data);
}

void mmio_and_writew(uintptr_t base, uint16_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_and_writew_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_and_writew);
  cmock_call_instance = (CMOCK_mmio_and_writew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_and_writew_CallInstance);
  Mock.mmio_and_writew_CallInstance = CMock_Guts_MemNext(Mock.mmio_and_writew_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_writew,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_writew,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_mmio_and_writew(CMOCK_mmio_and_writew_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint16_t data);
void CMockExpectParameters_mmio_and_writew(CMOCK_mmio_and_writew_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint16_t data)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void mmio_and_writew_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint16_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_and_writew_CALL_INSTANCE));
  CMOCK_mmio_and_writew_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_and_writew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_and_writew_CallInstance = CMock_Guts_MemChain(Mock.mmio_and_writew_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_and_writew(cmock_call_instance, base, data);
}

void mmio_and_writedw(uintptr_t base, uint32_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_and_writedw_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_and_writedw);
  cmock_call_instance = (CMOCK_mmio_and_writedw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_and_writedw_CallInstance);
  Mock.mmio_and_writedw_CallInstance = CMock_Guts_MemNext(Mock.mmio_and_writedw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_writedw,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_writedw,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_mmio_and_writedw(CMOCK_mmio_and_writedw_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint32_t data);
void CMockExpectParameters_mmio_and_writedw(CMOCK_mmio_and_writedw_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint32_t data)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void mmio_and_writedw_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint32_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_and_writedw_CALL_INSTANCE));
  CMOCK_mmio_and_writedw_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_and_writedw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_and_writedw_CallInstance = CMock_Guts_MemChain(Mock.mmio_and_writedw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_and_writedw(cmock_call_instance, base, data);
}

void mmio_writeb(uintptr_t base, uint8_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_writeb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_writeb);
  cmock_call_instance = (CMOCK_mmio_writeb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_writeb_CallInstance);
  Mock.mmio_writeb_CallInstance = CMock_Guts_MemNext(Mock.mmio_writeb_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_writeb,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_writeb,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_mmio_writeb(CMOCK_mmio_writeb_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint8_t data);
void CMockExpectParameters_mmio_writeb(CMOCK_mmio_writeb_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint8_t data)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void mmio_writeb_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint8_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_writeb_CALL_INSTANCE));
  CMOCK_mmio_writeb_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_writeb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_writeb_CallInstance = CMock_Guts_MemChain(Mock.mmio_writeb_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_writeb(cmock_call_instance, base, data);
}

void mmio_writew(uintptr_t base, uint16_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_writew_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_writew);
  cmock_call_instance = (CMOCK_mmio_writew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_writew_CallInstance);
  Mock.mmio_writew_CallInstance = CMock_Guts_MemNext(Mock.mmio_writew_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_writew,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_writew,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_mmio_writew(CMOCK_mmio_writew_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint16_t data);
void CMockExpectParameters_mmio_writew(CMOCK_mmio_writew_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint16_t data)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void mmio_writew_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint16_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_writew_CALL_INSTANCE));
  CMOCK_mmio_writew_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_writew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_writew_CallInstance = CMock_Guts_MemChain(Mock.mmio_writew_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_writew(cmock_call_instance, base, data);
}

void mmio_writedw(uintptr_t base, uint32_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_writedw_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_writedw);
  cmock_call_instance = (CMOCK_mmio_writedw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_writedw_CallInstance);
  Mock.mmio_writedw_CallInstance = CMock_Guts_MemNext(Mock.mmio_writedw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_writedw,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_writedw,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_mmio_writedw(CMOCK_mmio_writedw_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint32_t data);
void CMockExpectParameters_mmio_writedw(CMOCK_mmio_writedw_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint32_t data)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void mmio_writedw_CMockExpect(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint32_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_writedw_CALL_INSTANCE));
  CMOCK_mmio_writedw_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_writedw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_writedw_CallInstance = CMock_Guts_MemChain(Mock.mmio_writedw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_writedw(cmock_call_instance, base, data);
}

uint8_t mmio_readb(uintptr_t base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_readb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_readb);
  cmock_call_instance = (CMOCK_mmio_readb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_readb_CallInstance);
  Mock.mmio_readb_CallInstance = CMock_Guts_MemNext(Mock.mmio_readb_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_readb,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mmio_readb(CMOCK_mmio_readb_CALL_INSTANCE* cmock_call_instance, uintptr_t base);
void CMockExpectParameters_mmio_readb(CMOCK_mmio_readb_CALL_INSTANCE* cmock_call_instance, uintptr_t base)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
}

void mmio_readb_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_readb_CALL_INSTANCE));
  CMOCK_mmio_readb_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_readb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_readb_CallInstance = CMock_Guts_MemChain(Mock.mmio_readb_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_readb(cmock_call_instance, base);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint16_t mmio_readw(uintptr_t base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_readw_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_readw);
  cmock_call_instance = (CMOCK_mmio_readw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_readw_CallInstance);
  Mock.mmio_readw_CallInstance = CMock_Guts_MemNext(Mock.mmio_readw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_readw,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mmio_readw(CMOCK_mmio_readw_CALL_INSTANCE* cmock_call_instance, uintptr_t base);
void CMockExpectParameters_mmio_readw(CMOCK_mmio_readw_CALL_INSTANCE* cmock_call_instance, uintptr_t base)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
}

void mmio_readw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_readw_CALL_INSTANCE));
  CMOCK_mmio_readw_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_readw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_readw_CallInstance = CMock_Guts_MemChain(Mock.mmio_readw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_readw(cmock_call_instance, base);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint32_t mmio_readdw(uintptr_t base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_readdw_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_readdw);
  cmock_call_instance = (CMOCK_mmio_readdw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_readdw_CallInstance);
  Mock.mmio_readdw_CallInstance = CMock_Guts_MemNext(Mock.mmio_readdw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_readdw,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mmio_readdw(CMOCK_mmio_readdw_CALL_INSTANCE* cmock_call_instance, uintptr_t base);
void CMockExpectParameters_mmio_readdw(CMOCK_mmio_readdw_CALL_INSTANCE* cmock_call_instance, uintptr_t base)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
}

void mmio_readdw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_readdw_CALL_INSTANCE));
  CMOCK_mmio_readdw_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_readdw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_readdw_CallInstance = CMock_Guts_MemChain(Mock.mmio_readdw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_readdw(cmock_call_instance, base);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint8_t mmio_and_readb(uintptr_t base, uint8_t mask)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_and_readb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_and_readb);
  cmock_call_instance = (CMOCK_mmio_and_readb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_and_readb_CallInstance);
  Mock.mmio_and_readb_CallInstance = CMock_Guts_MemNext(Mock.mmio_and_readb_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_readb,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_readb,CMockString_mask);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_mask, mask, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mmio_and_readb(CMOCK_mmio_and_readb_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint8_t mask);
void CMockExpectParameters_mmio_and_readb(CMOCK_mmio_and_readb_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint8_t mask)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_mask = mask;
}

void mmio_and_readb_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint8_t mask, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_and_readb_CALL_INSTANCE));
  CMOCK_mmio_and_readb_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_and_readb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_and_readb_CallInstance = CMock_Guts_MemChain(Mock.mmio_and_readb_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_and_readb(cmock_call_instance, base, mask);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint16_t mmio_and_readw(uintptr_t base, uint16_t mask)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_and_readw_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_and_readw);
  cmock_call_instance = (CMOCK_mmio_and_readw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_and_readw_CallInstance);
  Mock.mmio_and_readw_CallInstance = CMock_Guts_MemNext(Mock.mmio_and_readw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_readw,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_readw,CMockString_mask);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_mask, mask, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mmio_and_readw(CMOCK_mmio_and_readw_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint16_t mask);
void CMockExpectParameters_mmio_and_readw(CMOCK_mmio_and_readw_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint16_t mask)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_mask = mask;
}

void mmio_and_readw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint16_t mask, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_and_readw_CALL_INSTANCE));
  CMOCK_mmio_and_readw_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_and_readw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_and_readw_CallInstance = CMock_Guts_MemChain(Mock.mmio_and_readw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_and_readw(cmock_call_instance, base, mask);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint32_t mmio_and_readdw(uintptr_t base, uint32_t mask)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mmio_and_readdw_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mmio_and_readdw);
  cmock_call_instance = (CMOCK_mmio_and_readdw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mmio_and_readdw_CallInstance);
  Mock.mmio_and_readdw_CallInstance = CMock_Guts_MemNext(Mock.mmio_and_readdw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_readdw,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_base), (void*)(&base), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_mmio_and_readdw,CMockString_mask);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_mask, mask, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mmio_and_readdw(CMOCK_mmio_and_readdw_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint32_t mask);
void CMockExpectParameters_mmio_and_readdw(CMOCK_mmio_and_readdw_CALL_INSTANCE* cmock_call_instance, uintptr_t base, uint32_t mask)
{
  memcpy((void*)(&cmock_call_instance->Expected_base), (void*)(&base),
         sizeof(uintptr_t[sizeof(base) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_mask = mask;
}

void mmio_and_readdw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uintptr_t base, uint32_t mask, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mmio_and_readdw_CALL_INSTANCE));
  CMOCK_mmio_and_readdw_CALL_INSTANCE* cmock_call_instance = (CMOCK_mmio_and_readdw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mmio_and_readdw_CallInstance = CMock_Guts_MemChain(Mock.mmio_and_readdw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_mmio_and_readdw(cmock_call_instance, base, mask);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

