#ifndef INC_RCC_INTERFACE_H
#define INC_RCC_INTERFACE_H

#include "helpers.h"

/* BITS 31:30 are used as device mask. */
#define RCC_AHB_DEVICE_MASK  0
#define RCC_APB1_DEVICE_MASK U32_BIT(30)
#define RCC_APB2_DEVICE_MASK U32_BIT(31)
#define RCC_DEVICE_EN_MASK   (U32_BIT(30) | U32_BIT(31))

#define RCC_DMA1_EN (U32_BIT(0) | RCC_AHB_DEVICE_MASK)
#define RCC_DMA2_EN (U32_BIT(1) | RCC_AHB_DEVICE_MASK)
#define RCC_SRAMEN  (U32_BIT(2) | RCC_AHB_DEVICE_MASK)
#define RCC_CRCEN   (U32_BIT(6) | RCC_AHB_DEVICE_MASK)
#define RCC_FSMCEN  (U32_BIT(8) | RCC_AHB_DEVICE_MASK)
#define RCC_RNGEN   (U32_BIT(9) | RCC_AHB_DEVICE_MASK)
#define RCC_SDIOEN  (U32_BIT(10) | RCC_AHB_DEVICE_MASK)
#define RCC_USBHSEN (U32_BIT(11) | RCC_AHB_DEVICE_MASK)
#define RCC_OTGFSEN (U32_BIT(12) | RCC_AHB_DEVICE_MASK)
#define RCC_DVPEN   (U32_BIT(13) | RCC_AHB_DEVICE_MASK)
#define RCC_ETHMACEN (U32_BIT(14) | RCC_AHB_DEVICE_MASK)
#define RCC_ETHMACTXEN (U32_BIT(15) | RCC_AHB_DEVICE_MASK)
#define RCC_ETHMACRXEN (U32_BIT(16) | RCC_AHB_DEVICE_MASK)
#define RCC_BLECEN     (U32_BIT(16) | RCC_AHB_DEVICE_MASK)
#define RCC_BLESEN     (U32_BIT(17) | RCC_AHB_DEVICE_MASK)

#define RCC_AFIOEN (U32_BIT(0) | RCC_APB2_DEVICE_MASK)
#define RCC_IOPAEN (U32_BIT(2) | RCC_APB2_DEVICE_MASK)
#define RCC_IOPBEN (U32_BIT(3) | RCC_APB2_DEVICE_MASK)
#define RCC_IOPCEN (U32_BIT(4) | RCC_APB2_DEVICE_MASK)
#define RCC_IOPDEN (U32_BIT(5) | RCC_APB2_DEVICE_MASK)
#define RCC_IOPEEN (U32_BIT(6) | RCC_APB2_DEVICE_MASK)
#define RCC_ADC1EN (U32_BIT(9) | RCC_APB2_DEVICE_MASK)
#define RCC_ADC2EN (U32_BIT(10) | RCC_APB2_DEVICE_MASK)
#define RCC_TIM1EN (U32_BIT(11) | RCC_APB2_DEVICE_MASK)
#define RCC_SPI1EN (U32_BIT(12) | RCC_APB2_DEVICE_MASK)
#define RCC_TIM8EN (U32_BIT(13) | RCC_APB2_DEVICE_MASK)
#define RCC_USART1EN (U32_BIT(14) | RCC_APB2_DEVICE_MASK)
#define RCC_TIM9EN   (U32_BIT(19) | RCC_APB2_DEVICE_MASK)
#define RCC_TIM10EN  (U32_BIT(20) | RCC_APB2_DEVICE_MASK)

#define RCC_TIM2EN (U32_BIT(0) | RCC_APB1_DEVICE_MASK)
#define RCC_TIM3EN (U32_BIT(1) | RCC_APB1_DEVICE_MASK)
#define RCC_TIM4EN (U32_BIT(2) | RCC_APB1_DEVICE_MASK)
#define RCC_TIM5EN (U32_BIT(3) | RCC_APB1_DEVICE_MASK)
#define RCC_TIM6EN (U32_BIT(4) | RCC_APB1_DEVICE_MASK)
#define RCC_TIM7EN (U32_BIT(5) | RCC_APB1_DEVICE_MASK)
#define RCC_UART6EN (U32_BIT(6) | RCC_APB1_DEVICE_MASK)
#define RCC_UART7EN (U32_BIT(7) | RCC_APB1_DEVICE_MASK)
#define RCC_UART8EN (U32_BIT(8) | RCC_APB1_DEVICE_MASK)
#define RCC_WWDGEN  (U32_BIT(11) | RCC_APB1_DEVICE_MASK)
#define RCC_SPI2EN  (U32_BIT(14) | RCC_APB1_DEVICE_MASK)
#define RCC_SPI3EN  (U32_BIT(15) | RCC_APB1_DEVICE_MASK)
#define RCC_USART2EN (U32_BIT(17) | RCC_APB1_DEVICE_MASK)
#define RCC_USART3EN (U32_BIT(18) | RCC_APB1_DEVICE_MASK)
#define RCC_UART4EN  (U32_BIT(19) | RCC_APB1_DEVICE_MASK)
#define RCC_UART5EN  (U32_BIT(20) | RCC_APB1_DEVICE_MASK)
#define RCC_I2C1EN   (U32_BIT(21) | RCC_APB1_DEVICE_MASK)
#define RCC_I2C2EN   (U32_BIT(22) | RCC_APB1_DEVICE_MASK)
#define RCC_USBDEN   (U32_BIT(23) | RCC_APB1_DEVICE_MASK)
#define RCC_CAN1EN   (U32_BIT(25) | RCC_APB1_DEVICE_MASK)
#define RCC_CAN2EN   (U32_BIT(26) | RCC_APB1_DEVICE_MASK)
#define RCC_BKPEN    (U32_BIT(27) | RCC_APB1_DEVICE_MASK)
#define RCC_PWREN    (U32_BIT(28) | RCC_APB1_DEVICE_MASK)
#define RCC_DACEN    (U32_BIT(29) | RCC_APB1_DEVICE_MASK)

void rcc_enable_periph(uint32_t device);

void rcc_disable_periph(uint32_t device);

#endif
